name: Publish Docker image

on:
  push:
    tags:
      - 'v*'  # Esto ejecuta el workflow cuando creas un tag que empieza con "v"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repository
      uses: actions/checkout@v3

    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKER_TOKEN }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Build the Docker image
      run: docker build -t ${{ secrets.DOCKER_USERNAME }}/my_custom_nginx_image:${{ github.ref_name }} .

    - name: Push the Docker image
      run: docker push ${{ secrets.DOCKER_USERNAME }}/my_custom_nginx_image:${{ github.ref_name }}
